// Things cooks say to the mic, and the timer each should become: the regression suite for
// parseSpoken (spoken.corpus.test.ts runs every line). Written as a transcript would arrive:
// the speech model's own capitals and punctuation, digits or number words as it pleases.
//
// Each entry: [said, name, minutes, prep]
//  - name:    what belongs on the timer card. If the food is in src/data/foods.ts (exactly, or as
//             its singular/plural) it is that entry's name verbatim; otherwise the cook's own words
//             for the food, lower case with one capital at the front. '' if no food was said.
//  - minutes: the time in minutes (1.5 = 90 seconds), or null if no time was said.
//  - prep:    true only if they said prep / prepare / prepped / prepping.
//
// When adding lines: write what a person would expect on the card, not what the parser gives
// today, then fix the parser. The name is the cook's own word even where the food list knows it
// by another ("fries" stays Fries, not the list's Chips; "veg" stays Veg): only an entry's exact
// name, or its singular/plural, snaps to the list. No mishearings here; those are in spoken.test.ts.

export const CORPUS: readonly (readonly [said: string, name: string, minutes: number | null, prep: boolean])[] = [
  ['Start a timer for this pork, for 20 minutes', 'Pork', 20, false],
  ['Start a 10 minute rice timer', 'Rice', 10, false],

  // Bare "food number" / "food number unit"
  ['Rice 10', 'Rice', 10, false],
  ['pasta 8 minutes', 'Pasta', 8, false],
  ['chicken thighs 35 minutes', 'Chicken thighs', 35, false],
  ['Salmon 12 mins', 'Salmon', 12, false],
  ['carrots 20 minutes', 'Carrots', 20, false],
  ['Broccoli 6 min', 'Broccoli', 6, false],
  ['Lasagne 40', 'Lasagne', 40, false],
  ['sausages 20 mins', 'Sausages', 20, false],
  ['Turkey crown 3 hours', 'Turkey crown', 180, false],
  ['Beef stew 90 minutes', 'Beef stew', 90, false],
  ['soup 15 minutes', 'Soup', 15, false],
  ['Halloumi 8 minutes', 'Halloumi', 8, false],
  ['Nachos 10 minutes', 'Nachos', 10, false],
  ['hummus 5 minutes', 'Hummus', 5, false],

  // Food first with number words, hyphenated adjectives, hours
  ['Rice ten minutes', 'Rice', 10, false],
  ['Turkey forty five minutes', 'Turkey', 45, false],
  ['Lamb an hour and a half', 'Lamb', 90, false],
  ['Bread half an hour', 'Bread', 30, false],
  ['Stock a quarter of an hour', 'Stock', 15, false],
  ['Casserole three quarters of an hour', 'Casserole', 45, false],
  ['Brisket two and a half hours', 'Brisket', 150, false],
  ['Beef stew one hour twenty', 'Beef stew', 80, false],
  ['Chicken wings two hours thirty', 'Chicken wings', 150, false],
  ['Eggs a minute', 'Eggs', 1, false],
  ['Salmon ninety seconds', 'Salmon', 1.5, false],
  ['Eggs two minutes thirty seconds', 'Eggs', 2.5, false],
  ['Boiled eggs six and a half minutes', 'Boiled eggs', 6.5, false],
  ['Gammon two hrs', 'Gammon', 120, false],
  ['Chilli forty five mins', 'Chilli', 45, false],
  ['Risotto twenty five minutes', 'Risotto', 25, false],
  ['Pizza fifteen minutes', 'Pizza', 15, false],
  ['Jollof rice thirty five minutes', 'Jollof rice', 35, false],
  ['Jerk chicken forty minutes', 'Jerk chicken', 40, false],
  ['Poutine twenty minutes', 'Poutine', 20, false],

  // Time first
  ['Ten minutes for the rice', 'Rice', 10, false],
  ['Forty five minutes for the roast potatoes', 'Roast potatoes', 45, false],
  ['An hour for the lamb shank', 'Lamb shank', 60, false],
  ['Half an hour for the bread', 'Bread', 30, false],
  ['Twenty minutes on the carrots', 'Carrots', 20, false],
  ['Ninety seconds for the salmon', 'Salmon', 1.5, false],
  ['Six minutes for the eggs', 'Eggs', 6, false],
  ['Two and a half hours for the brisket', 'Brisket', 150, false],
  ['One hour and twenty minutes for the beef stew', 'Beef stew', 80, false],
  ['A quarter of an hour for the dal', 'Dal', 15, false],
  ['Three quarters of an hour for the casserole', 'Casserole', 45, false],
  ['Twelve minutes for the gravy', 'Gravy', 12, false],
  ['Thirty minutes for the nut roast', 'Nut roast', 30, false],
  ['Twenty minutes for the halloumi fries', 'Halloumi fries', 20, false],
  ['Forty minutes for the beef bourguignon', 'Beef bourguignon', 40, false],

  // Time in the middle
  ['A 10 minute rice timer', 'Rice', 10, false],
  ['a 45 minute timer for roast potatoes', 'Roast potatoes', 45, false],
  ['Set a 20 minute timer for the pork chops', 'Pork chops', 20, false],
  ['Make a 12 minute gravy timer', 'Gravy', 12, false],
  ['Start a 90 second salmon timer', 'Salmon', 1.5, false],
  ['Put on a six minute egg timer', 'Eggs', 6, false],
  ['Do a fifteen minute dal timer', 'Dal', 15, false],
  ['Give me a thirty minute bread timer', 'Bread', 30, false],
  ['Add a forty five minute lasagne timer', 'Lasagne', 45, false],
  ['Create a two hour turkey crown timer', 'Turkey crown', 120, false],
  ['Set a twenty five minute risotto timer', 'Risotto', 25, false],
  ['a ten-minute rice timer', 'Rice', 10, false],
  ['a two-hour brisket timer', 'Brisket', 120, false],
  ['Set an eight minute nachos timer', 'Nachos', 8, false],
  ['Make a twenty minute jambalaya timer', 'Jambalaya', 20, false],

  // Imperative: set / start / give me / put on / make / add / create / do
  ['Set a timer for the chicken thighs, thirty five minutes', 'Chicken thighs', 35, false],
  ['Start the oven chips for eighteen minutes', 'Oven chips', 18, false],
  ['Give me a timer for the sausages, twenty minutes', 'Sausages', 20, false],
  ['Put on the pasta for nine minutes', 'Pasta', 9, false],
  ['Make a timer for the dumplings, twelve minutes', 'Dumplings', 12, false],
  ['Add twenty minutes for the roast vegetables', 'Roast vegetables', 20, false],
  ['Create a timer, thirty minutes, for the casserole', 'Casserole', 30, false],
  ['Do a timer for the ribs, two hours', 'Ribs', 120, false],
  ['Start a timer for the beef bourguignon, forty five minutes', 'Beef bourguignon', 45, false],
  ['prep the carrots for twenty minutes', 'Carrots', 20, true],
  ['prepare a forty five minute timer for roast potatoes', 'Roast potatoes', 45, true],
  ['Get the lamb prepped, an hour and a half', 'Lamb', 90, true],
  ['carrots twenty minutes, prep', 'Carrots', 20, true],
  ['Start prepping the gravy for twelve minutes', 'Gravy', 12, true],
  ['Put the pizza dough on to prep for forty minutes', 'Pizza dough', 40, true],
  ['Set a prep timer for the onions, ten minutes', 'Onions', 10, true],
  ['prep this jollof rice for twenty five minutes', 'Jollof rice', 25, true],
  ['Give the nut roast a thirty minute prep', 'Nut roast', 30, true],
  ['Prepare some hummus, fifteen minutes', 'Hummus', 15, true],
  ['prepping the beef bourguignon, forty minutes', 'Beef bourguignon', 40, true],
  ['Set a timer for our turkey, three hours', 'Turkey', 180, false],
  ['Put my rice on for ten minutes', 'Rice', 10, false],
  ['Start their pizza for fifteen minutes', 'Pizza', 15, false],
  ['Give that lamb an hour', 'Lamb', 60, false],
  ['Time this chicken for twenty minutes', 'Chicken', 20, false],

  // Polite questions
  ['Can you time my chicken drumsticks for twenty minutes please', 'Chicken drumsticks', 20, false],
  ['Could you set a timer for the lasagne, forty minutes', 'Lasagne', 40, false],
  ['Would you start a timer for the salmon please', 'Salmon', null, false],
  ['Could you put the pie in the oven for thirty five minutes please', 'Pie', 35, false],
  ['Would you prep the leeks for fifteen minutes please', 'Leeks', 15, true],
  ['Could you start the rice for ten minutes please', 'Rice', 10, false],
  ['Could you count down fifteen minutes for the veg', 'Veg', 15, false],
  ['Can you set a half hour timer for the stew please', 'Stew', 30, false],
  ['Would you give me a timer for the naan, please', 'Naan', null, false],
  ['Can you prepare a timer for the falafel, twelve minutes', 'Falafel', 12, true],
  ['Could you put on a timer for the jerk chicken, forty minutes', 'Jerk chicken', 40, false],
  ['Can you set a timer for the poke bowl, ten minutes please', 'Poke bowl', 10, false],
  ['Could you set a timer for the paneer tikka, fifteen minutes', 'Paneer tikka', 15, false],

  // Statements
  ['The lamb wants another hour', 'Lamb', 60, false],
  ["I'm putting the chicken in for forty minutes", 'Chicken', 40, false],
  ['The pie is going in the oven for thirty five minutes', 'Pie', 35, false],
  ['I need twenty minutes on the potatoes', 'Potatoes', 20, false],
  ['Remind me about the bread in twenty five minutes', 'Bread', 25, false],
  ['Tell me when the eggs have had six minutes', 'Eggs', 6, false],
  ['Let me know in ten minutes about the rice', 'Rice', 10, false],
  ['Count down fifteen minutes for the veg', 'Veg', 15, false],
  ['The dal wants twenty five minutes', 'Dal', 25, false],
  ['The gravy needs another ten minutes', 'Gravy', 10, false],
  ['The lasagne is going in the oven for forty minutes', 'Lasagne', 40, false],
  ['I need an hour and a half for the lamb shank', 'Lamb shank', 90, false],
  ['The turkey crown wants three hours', 'Turkey crown', 180, false],
  ['I need ten more minutes on the risotto', 'Risotto', 10, false],
  ['The roast potatoes need forty five minutes', 'Roast potatoes', 45, false],
  ["I'm prepping the beef bourguignon, forty minutes", 'Beef bourguignon', 40, true],
  ['The jambalaya wants twenty minutes', 'Jambalaya', 20, false],
  ['Remind me about the halloumi fries in eight minutes', 'Halloumi fries', 8, false],
  ['Tell me when the vindaloo has had twenty minutes', 'Vindaloo', 20, false],
  ['I need thirty minutes on the shakshuka', 'Shakshuka', 30, false],
  ['The falafel is going in the air fryer for twelve minutes', 'Falafel', 12, false],
  ['The chicken korma wants thirty minutes', 'Chicken korma', 30, false],
  ['Put the minestrone on for twenty five minutes', 'Minestrone', 25, false],
  ['I need forty minutes on the egusi soup', 'Egusi soup', 40, false],
  ['Give the suya skewers ten minutes', 'Suya skewers', 10, false],
  ['The gazpacho needs chilling, twenty minutes', 'Gazpacho', 20, false],

  // Addressed to the robot
  ['Hey Sizzle, start the rice for ten minutes', 'Rice', 10, false],
  ['Sizzle, give the lamb an hour', 'Lamb', 60, false],
  ['Okay Sizzle, set a timer for the roast chicken, ninety minutes', 'Roast chicken', 90, false],
  ['Hey Sizzle, prep the carrots for twenty minutes', 'Carrots', 20, true],
  ['Sizzle, time the turkey', 'Turkey', null, false],
  ['Okay Sizzle, twelve minutes for the gravy', 'Gravy', 12, false],
  ['Hey Sizzle, can you do a timer for the halloumi, eight minutes', 'Halloumi', 8, false],
  ['Sizzle, start a timer for the jollof rice, thirty minutes', 'Jollof rice', 30, false],
  ['Okay Sizzle, prepare the gravy, twelve minutes', 'Gravy', 12, true],
  ['Hey Sizzle, twenty minutes', '', 20, false],
  ['Sizzle, the laksa needs twenty minutes', 'Laksa', 20, false],

  // Trailing chatter
  ['Set a timer for the pasta, nine minutes, thanks', 'Pasta', 9, false],
  ['Start the rice for ten minutes, cheers', 'Rice', 10, false],
  ['Give the chicken thighs thirty five minutes if you can', 'Chicken thighs', 35, false],
  ['Can you time the eggs for six minutes, please', 'Eggs', 6, false],
  ['Prep the leeks for fifteen minutes, if you can', 'Leeks', 15, true],
  ['Put the lasagne in the oven for forty minutes, thanks', 'Lasagne', 40, false],
  ['Set a timer for the halloumi fries, cheers', 'Halloumi fries', null, false],
  ['Start a timer for the jambalaya, please', 'Jambalaya', null, false],

  // Determiners
  ['These roast potatoes need forty five minutes', 'Roast potatoes', 45, false],
  ['Start a timer for those sausages, ten minutes', 'Sausages', 10, false],
  ['Put some rice on for ten minutes', 'Rice', 10, false],
  ['He wants his steak for four minutes', 'Steak', 4, false],
  ['Start her pasta for nine minutes', 'Pasta', 9, false],

  // Plurals/singulars relative to the food list
  ['A roast potato timer, forty five minutes', 'Roast potatoes', 45, false],
  ['Egg six minutes', 'Eggs', 6, false],
  ['Onion ten minutes', 'Onions', 10, false],
  ['Mushroom eight minutes', 'Mushrooms', 8, false],
  ['Chicken wing twenty minutes', 'Chicken wings', 20, false],
  ['Dumpling twelve minutes', 'Dumplings', 12, false],
  ['Pancake three minutes', 'Pancakes', 3, false],
  ['Bread roll ten minutes', 'Bread rolls', 10, false],
  ['Cookie twelve minutes', 'Cookies', 12, false],

  // Appliance phrases, British and American (not part of the name)
  ['Put the rice on the hob for ten minutes', 'Rice', 10, false],
  ['Put the cheese toastie under the grill for five minutes', 'Cheese toastie', 5, false],
  ['Put the halloumi fries in the air fryer for twelve minutes', 'Halloumi fries', 12, false],
  ['Put the steak on the stove for four minutes', 'Steak', 4, false],
  ['Put the onions in the pan for eight minutes', 'Onions', 8, false],

  // Roast / Baked / Boiled / Fried / Grilled / Toast keep their first word
  ['Roast potatoes forty five minutes', 'Roast potatoes', 45, false],
  ['Baked apples twenty minutes', 'Baked apples', 20, false],
  ['Boiled eggs six minutes', 'Boiled eggs', 6, false],
  ['Fried rice eight minutes', 'Fried rice', 8, false],
  ['Grilled octopus ten minutes', 'Grilled octopus', 10, false],
  ['Toast three minutes', 'Toast', 3, false],
  ['Roast turkey three hours', 'Roast turkey', 180, false],
  ['Roast lamb ninety minutes', 'Roast lamb', 90, false],
  ['Roast chicken an hour and a half', 'Roast chicken', 90, false],
  ['Fried eggs four minutes', 'Fried eggs', 4, false],

  // Dishes not in the food list
  ['Empanadas twenty minutes', 'Empanadas', 20, false],
  ['Kimchi fried rice ten minutes', 'Kimchi fried rice', 10, false],
  ['Peking duck ninety minutes', 'Peking duck', 90, false],
  ['Sticky rice twenty five minutes', 'Sticky rice', 25, false],
  ['Egg fried rice eight minutes', 'Egg fried rice', 8, false],
  ['Butter chicken twenty five minutes', 'Butter chicken', 25, false],
  ['Chicken tikka masala thirty minutes', 'Chicken tikka masala', 30, false],
  ['Falafel wrap five minutes', 'Falafel wrap', 5, false],
  ['Macaroni cheese twenty minutes', 'Macaroni cheese', 20, false],
  ['Plantain eight minutes', 'Plantain', 8, false],
  ['Bao buns twelve minutes', 'Bao buns', 12, false],
  ['Beef bourguignon two hours', 'Beef bourguignon', 120, false],
  ['Coq au vin ninety minutes', 'Coq au vin', 90, false],
  ['Ratatouille forty minutes', 'Ratatouille', 40, false],
  ['Miso soup five minutes', 'Miso soup', 5, false],
  ['Green curry twenty five minutes', 'Green curry', 25, false],
  ['Gumbo forty five minutes', 'Gumbo', 45, false],
  ['Crab cakes twelve minutes', 'Crab cakes', 12, false],
  ['Fish tacos ten minutes', 'Fish tacos', 10, false],
  ['Prawn cocktail five minutes', 'Prawn cocktail', 5, false],
  ['Can you do a timer for the onigiri, five minutes', 'Onigiri', 5, false],

  // Duration forms: digit hour/minute mixes, approximations, "more/another", abbreviations
  ['Beef stew 1 hour 20', 'Beef stew', 80, false],
  ['Chicken wings 2 hours 30 minutes', 'Chicken wings', 150, false],
  ['Give the rice a couple of minutes', 'Rice', 2, false],
  ['The potatoes need about twenty minutes', 'Potatoes', 20, false],
  ['Around half an hour for the stew', 'Stew', 30, false],
  ['Roughly forty five minutes for the roast potatoes', 'Roast potatoes', 45, false],
  ['Twenty minutes or so for the carrots', 'Carrots', 20, false],
  ['Ninety secs for the salmon', 'Salmon', 1.5, false],
  ['Fries fifteen minutes', 'Fries', 15, false],
  ['Sweet potato fries twenty minutes', 'Sweet potato fries', 20, false],
  ['Wedges twenty five minutes', 'Wedges', 25, false],
  ['Sushi rice twenty minutes', 'Sushi rice', 20, false],
  ['Yorkshire pudding twenty minutes', 'Yorkshire puddings', 20, false],
  ['Fish finger twelve minutes', 'Fish fingers', 12, false],
  ['Spring roll ten minutes', 'Spring rolls', 10, false],

  // More prep, in varied positions
  ['Prep the roast turkey, three hours', 'Roast turkey', 180, true],
  ['Prepping the halloumi fries, twelve minutes', 'Halloumi fries', 12, true],
  ['Prepare a timer for the dal, fifteen minutes', 'Dal', 15, true],
  ['Prep my chicken thighs for thirty minutes', 'Chicken thighs', 30, true],
  ['Prep those roast potatoes, forty five minutes', 'Roast potatoes', 45, true],
  ['Prepare the coq au vin, an hour and a half', 'Coq au vin', 90, true],
  ['Prep the lasagne for forty minutes', 'Lasagne', 40, true],
  ['Would you prepare the samosas, twelve minutes', 'Samosas', 12, true],
  ['Prep the sushi rice, twenty minutes', 'Sushi rice', 20, true],
  ['Prep the palak paneer for twenty minutes', 'Palak paneer', 20, true],

  // No time at all
  ['Chicken thighs.', 'Chicken thighs', null, false],
  ['Start the dumplings', 'Dumplings', null, false],
  ['Prep the carrots', 'Carrots', null, true],
  ['The pie is going in the oven', 'Pie', null, false],
  ['Hey Sizzle, start the naan', 'Naan', null, false],

  // Time but no food
  ['Set a timer for thirty minutes', '', 30, false],
  ['Give me ten minutes', '', 10, false],
  ['Start a thirty second timer', '', 0.5, false],
  ['Can you do a thirty minute timer please', '', 30, false],
  ['Count down fifteen minutes', '', 15, false],
  ['Prep for twenty minutes', '', 20, true],
  ['One hour timer', '', 60, false],
  ['Twenty minutes, please', '', 20, false],
] as const satisfies readonly (readonly [said: string, name: string, minutes: number | null, prep: boolean])[]
